#units of measures are reported in seconds
serverLocation="http://asrncss.ddns.net"
tone_unit_analysis_window=0.2
tone_unit_energy_loss=0.6
tone_unit_energy_quartile=0
tone_unit_minimum_to_search=3
tone_unit_max_iterations=10
tone_unit_min_length=1.5
hmm_pretrained="./auxfiles/cryhmm.hmm"
hmm_pretrained_noncry="./auxfiles/noncryhmm.hmm"
energy_analysis_window=0.1
asr_cry_detection_h_ratio_thr=0.1
asr_cry_detection_maximum_compression_ratio_of_speech=4
asr_cry_detection_maximum_avg_log_of_speech=-1
asr_cry_detection_default_nonword="Grazie"
asr_cry_detection_maximum_avg_log_of_noise=-0.2